// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://aeiphqwexxqmcjteazjl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFlaXBocXdleHhxbWNqdGVhempsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI2ODIwNzUsImV4cCI6MjA2ODI1ODA3NX0.voRXNhv2g0j8dofS7mWqBKi2pDuFVxk5D3JIzxGPaMY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});